# Generated by Django 2.2.4 on 2019-09-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
    ]
