# Generated by Django 2.2.4 on 2019-09-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190904_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='productvariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.ProductVariant'),
        ),
    ]
