# Generated by Django 2.2.4 on 2019-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190904_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='color',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size',
            new_name='title',
        ),
    ]
