# Generated by Django 2.2.4 on 2019-09-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
