# Generated by Django 2.2.5 on 2019-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('boys', 'Boys'), ('girls', 'Girls')], default='man', max_length=120),
        ),
    ]
