# Generated by Django 2.2.5 on 2019-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('boys', 'Boys'), ('girls', 'Girls')], default='men', max_length=120),
        ),
    ]
