# Generated by Django 2.2.6 on 2019-10-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191012_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
