# Generated by Django 2.2.6 on 2019-10-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191019_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='brand',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='type',
            new_name='title',
        ),
    ]
