# Generated by Django 2.2.5 on 2019-09-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20190928_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='payment_option',
        ),
    ]
