# Generated by Django 2.2.5 on 2019-09-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190913_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariant'),
        ),
    ]
